name: Build Documentation

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Concatenate Markdown Files
      run: |
        mkdir -p concatenated_docs
        cat docs/source/*.md > concatenated_docs/Triform_Documentation.md

    - name: Upload Concatenated Document
      uses: actions/upload-artifact@v2
      with:
        name: Triform_Documentation
        path: concatenated_docs/Triform_Documentation.md
